apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openidentity.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openidentity.labels" . | nindent 4 }}
data:
  DB_KIND: "postgresql"
  DB_URL: "jdbc:postgresql://{{ include "openidentity.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}"
  DB_USERNAME: {{ .Values.postgres.username | quote }}
  HTTP_PORT: {{ .Values.config.httpPort | quote }}
  SESSION_IDLE_TIMEOUT_SECONDS: {{ .Values.config.sessionIdleTimeoutSeconds | quote }}
