apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openidentity.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openidentity.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  OPENIDENTITY_ADMIN_BOOTSTRAP_TOKEN: {{ .Values.secrets.adminBootstrapToken | quote }}
  OPENIDENTITY_SECRET_PROTECTION_KEY: {{ .Values.secrets.secretProtectionKey | quote }}
  OPENIDENTITY_JWT_PRIVATE_KEY_PEM: {{ .Values.secrets.jwtPrivateKeyPem | quote }}
  OPENIDENTITY_JWT_PUBLIC_KEY_PEM: {{ .Values.secrets.jwtPublicKeyPem | quote }}
