apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: openidentity-auth
  namespace: openidentity
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openidentity-auth
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
