ALTER TABLE organization ADD COLUMN IF NOT EXISTS logo_text VARCHAR(64);
ALTER TABLE organization ADD COLUMN IF NOT EXISTS primary_color VARCHAR(16);
ALTER TABLE organization ADD COLUMN IF NOT EXISTS accent_color VARCHAR(16);
ALTER TABLE organization ADD COLUMN IF NOT EXISTS locale VARCHAR(32);
